### ISSUE TITLE
Asset list- Filter for asset class: ventilator

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5925] opened 2023-07-26 06:36 UTC
In advance filter in the asset list (https://care.coronasafe.in/assets) shows a filter based on "Asset Class". Add the option for "Ventilator"

**Comment by nihal467** [comment] 2023-07-26 06:45
@aparnacoronasafe already we have a issue, closing this, as it is duplicate of : https://github.com/coronasafe/care_fe/issues/5915

**Closed as completed** 2023-07-26 06:46 UTC
Labels: P1
