### ISSUE TITLE
Show Selected Medicine in the Placeholder of the Medicine Component

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9595] opened 2024-12-27 11:42 UTC
**Describe the bug**

Currently, when a medicine is selected, the placeholder does not update to show the selected medicine in the prescription module.

**To Reproduce**

1. Go to 'any active consultation, click on medicine
2. Add a medicine and select one out of the dropdown

**Expected behavior**

- [ ] The selected medicine should be displayed in the placeholder of the dropdown component.

**Screenshots**

![Image](https://github.com/user-attachments/assets/abd2a34b-cc03-4e36-91f0-21c567de3f99)

**Comment by AdityaJ2305** [comment] 2024-12-27 11:44
Hey @nihal467 , I would like to work on this issue

**Comment by AdityaJ2305** [comment] 2024-12-27 11:53
https://github.com/user-attachments/assets/0927e483-b193-42b7-9cd5-c4c1d4b17278


Am I misunderstanding the issue again, or is it genuinely working fine on my end? 😅

**Comment by nihal467** [comment] 2024-12-27 12:00
https://care-staging.ohc.network/facility/5880ad89-57ae-4994-af50-7d99855e7f9d/patient/050080f2-252b-46e4-a44e-eba324693c16/consultation/40396cc3-e859-419e-a659-c6d59cc6b81f/prescriptions

@AdityaJ2305 try to add it here

**Comment by AdityaJ2305** [comment] 2024-12-27 12:01
> https://care-staging.ohc.network/facility/5880ad89-57ae-4994-af50-7d99855e7f9d/patient/050080f2-252b-46e4-a44e-eba324693c16/consultation/40396cc3-e859-419e-a659-c6d59cc6b81f/prescriptions
> 
> [@AdityaJ2305](https://github.com/AdityaJ2305) try to add it here

Working fine 

https://github.com/user-attachments/assets/dd344d99-406f-4ee6-bb4d-62a2857b3956

**Comment by nihal467** [comment] 2024-12-27 12:09
@AdityaJ2305 can you do a hardrefresh before you try it

**Comment by AdityaJ2305** [comment] 2024-12-27 12:13
Sure, I’ve tried it on `care.ohc` and `care-staging.ohc` , and it’s working fine!

**Comment by AdityaJ2305** [comment] 2024-12-27 12:46
Ah, got it! The issue only occurs when typing and selecting, not when selecting directly from the dropdown.

**Comment by Jacobjeevan** [comment] 2024-12-27 12:56
> ⚠️ **Refrain from assigning this issue to yourself if you have another `P1` issue assigned that is not yet closed.**

@AdityaJ2305

**Comment by AdityaJ2305** [comment] 2024-12-27 13:00
> > ⚠️ **Refrain from assigning this issue to yourself if you have another `P1` issue assigned that is not yet closed.**
> 
> [@AdityaJ2305](https://github.com/AdityaJ2305)

Sorry about that, I thought the first issue was almost resolved. I’ll make sure to follow this in the future.

**Comment by Jacobjeevan** [comment] 2024-12-27 13:05
> > > ⚠️ **Refrain from assigning this issue to yourself if you have another `P1` issue assigned that is not yet closed.**
> > 
> > 
> > [@AdityaJ2305](https://github.com/AdityaJ2305)
> 
> Sorry about that, I thought the first issue was almost resolved. I’ll make sure to follow this in the future.

And please get the issue assigned first before you open a PR. Good to see your enthusiasm, but the issue is others will start doing the same and it just becomes a race of who can open a PR first 😅

**Comment by JavidSumra** [comment] 2024-12-27 14:10
is there anyone working on this issue?

**Comment by SathishAdithiyaaSV** [comment] 2024-12-27 14:17
I would like to work on this issue. Can you please assign this to me?

**Closed as completed** 2024-12-28 05:48 UTC
Labels: question, P1, needs-triage
