### ISSUE TITLE
Total Occupancy bed Tooltip in the facility card is clipping in mobile view

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9230] opened 2024-11-28 11:50 UTC
**Describe the bug**

The tooltip displaying the total bed occupancy on the facility card is clipping in mobile view.

**To Reproduce**

1. Go to https://care-staging.ohc.network/facility
2. Switch to the mobile view.
3. Click on the "Total Occupancy" tooltip.

**Expected behavior**

- [ ] The tooltip text should be fully visible and properly displayed in mobile view.

**Screenshots**

![Image](https://github.com/user-attachments/assets/823db85e-88f8-4cdc-918b-3eb585342e6d)

**Comment by Rishith25** [comment] 2024-11-28 12:02
@nihal467 I would like to work on this issue

**Comment by Mahendar0701** [comment] 2024-11-28 12:02
I want to work on this. Please assign this to me.

**Comment by DonXavierdev** [comment] 2024-11-28 12:35
I would like to work on this. Please assign this to me.

**Comment by AdityaJ2305** [comment] 2024-11-28 12:38
Hey @nihal467  I am not able to reproduce it on localhost (synced) and on staging url it is showing 0 Facility

**Comment by rajku-dev** [comment] 2024-12-01 01:44
@nihal467 Can I work on this issue?

**Closed as completed** 2024-12-17 08:16 UTC
