### ISSUE TITLE
filters in Facility>user page

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8106] opened 2024-07-03 10:05 UTC
**Is your feature request related to a problem? Please describe.**
It is very difficult to find out how many nurses/doctors are allocated within a facility, either as staff in the facility or for remote support

**Describe the solution you'd like**
Add filter to facility>user page with the following options

- [ ] User role (Doctor/staff/nurse/pharmacist/volunteer etc)

- [ ] Access type (Show home facility /others/show all)

**Comment by tomahawk-pilot** [comment] 2024-08-19 20:04
@yadev64

**Comment by yadev64** [comment] 2024-08-19 20:06
I would like to take up this issue.

**Comment by bodhish** [comment] 2024-09-06 09:36
@yadev64 if you are working on it, don't pick the solution listed. Feel free to ideate. 
I am not sure if its the right way to list users also. This can be a good time to build a better UI/UX

**Comment by NikhilGolla72** [comment] 2024-12-14 19:28
@bodhish @Jacobjeevan @dauntlessnomad @gigincg i would like to contribute to this issue, it no one is assigned,could you please assign me to this.

**Comment by nihal467** [comment] 2024-12-19 04:50
@NikhilGolla72 the issue is assigned to you, do check the comment made by bodhi

**Comment by nihal467** [comment] 2024-12-31 09:33
not a requirement based on the current develop

**Closed as not planned by nihal467** 2024-12-31 09:33 UTC
Labels: Work in Progress
