### ISSUE TITLE
Add Consultation button is disabled after patient is discharged

### ISSUE THREAD

**Issue by yash-learner** [coronasafe/care_fe#9055] opened 2024-11-08 09:41 UTC
**Describe the bug**
Can not add a consultation via UI after a patient is discharged as the `Add Consultation` button is disabled. It is can be still accessed via visiting the route.
 
**To Reproduce**

1. Go to patient with a consultation. - Visit consultation page
2. Click `Manage Patient` 
3. Click `Discharge from Care`
4. Now, you can notice `Add consultation` button is disabled but you can still access the route.

**Expected behavior**
I think the button should be enabled and should be possible to add a new consultation.

**Screenshots**

https://github.com/user-attachments/assets/9a835589-ba85-44b7-89be-e4eb74af66ba

**Comment by Rishith25** [comment] 2024-11-08 09:54
Can I work on this

**Comment by yash-learner** [comment] 2024-11-08 11:13
@rithviknishad @Jacobjeevan  👆

**Comment by nihal467** [comment] 2024-11-08 13:01
@yash-learner It is an expected behavior, once a patient is discharged, without readmission we shouldn't allow new consultation

**Comment by Sancharisingh** [comment] 2024-11-10 06:44
Hello @nihal467 
I noticed that the 'Add Consultation' button is disabled after a patient is discharged. Since this behavior is marked as expected, could you clarify if:

Is this the feature's final behavior, or is it still a work in progress?
Are there any specific conditions under which this functionality might change?
Thanks.

**Comment by Rustix69** [comment] 2024-11-11 06:48
I would like work on this, if that's okay. And can you clarify the expected behavior.

**Comment by SwanandBhuskute** [comment] 2024-11-11 18:51
I would like to work on this issue @rithviknishad @nihal467 , pls assign me

**Comment by rithviknishad** [comment] 2024-11-12 02:13
As discussed, the "Add consultation" button has no use based on the following:

When a patient is registered to a facility, and a consultation has yet to be created, the "Create Consultation" banner present in "no consultation filed" is sufficient. 
For re-admission purposes, there exists a workflow to properly validate a patient through the Add Patient Details form itself by matching the phone number and date of birth. Hence this "Add Consultation" button serves no use.

So we can remove "Add Consultation" button to avoid confusion.

cc: @nihal467

**Closed as completed** 2024-11-17 14:35 UTC
Labels: good first issue
