### ISSUE TITLE
Presets for Infusion/Output

### ISSUE THREAD

**Issue by sam9111** [coronasafe/care_fe#2011] opened 2022-01-07 16:50 UTC
Preset(default) values for "Infusions" and "Outputs" under I/O Balance editor can be set.

**Comment by gigincg** [comment] 2022-01-08 16:09
This would work like a set of buttons with the common infusions and outputs. If the count is too big to be listed, we'd have to use a searchable dropdown

**Comment by aparnacoronasafe** [comment] 2022-06-17 09:56
@gigincg what is intended here?

**Comment by gigincg** [comment] 2022-06-17 11:27
@aparnacoronasafe Need to reconfirm with Dr. Athul, the issue is not descriptive enough.

**Comment by aparnacoronasafe** [comment] 2022-08-19 13:19
Cant make sense of this either. Closing this issue

**Closed as completed by aparnacoronasafe** 2022-08-19 13:19 UTC
