### ISSUE TITLE
Design Enhancement Scope in Header Part of all tab in CARE

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6648] opened 2023-11-16 04:00 UTC
**Describe the bug**

We are having Facility, Patient, Assets, Sample Test, Shifting. Resource. External Results, Users homepage, whenever we open these all pages, using the sidebar navigation, there are few components in common on the header part : 

- Total Count
- Search Box for filtering data
- Advance filter and other co-related buttons
-  Import/exports button

When we switch between all these tab, we can feel all these common components are places in multiple way which doesn't give a consistency feel.

**To Reproduce**

1. Go to /facility
2. Using the sidebar keep on switching between the tabs
3. See error

**Expected behavior**

An consistent design for the entire head part of the all pages where this components are present

Note: Whoever wishes to work on this issue, get the mock-up design approved in the EOD call, then only, the issue will be assigned to the respective author.

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/88d10c38-654e-4bcb-9634-aecef52963b8)
![image](https://github.com/coronasafe/care_fe/assets/57055998/5644bb31-9bd1-498c-9191-0ac3cbdb8d7c)
![image](https://github.com/coronasafe/care_fe/assets/57055998/d15695c7-8e3b-4338-b2a7-d784c86bbdf7)

**Comment by rithviknishad** [comment] 2023-11-16 04:07
We should also make the placement of the Add/Create and the Advanced Filter of Asset/Patient/User/... consistent

**Comment by rithviknishad** [comment] 2024-02-29 16:35
Closing as duplicate of #7316

**Closed as not planned by rithviknishad** 2024-02-29 16:35 UTC
Labels: UI-Enhancement
