### ISSUE TITLE
In the Fields of Login Page the placeholder and the presaved password and username gets overwritten

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#4138] opened 2022-11-28 04:41 UTC
**Describe the bug**
In the Fields of Login Page the placeholder and the presaved password and username gets overwritten

**To Reproduce**

1. Go to Login Page

**Expected behavior**
The placeholder should not be overwritten.

**Screenshots**
![Screenshot 2022-11-28 100359](https://user-images.githubusercontent.com/59426397/204195450-36d88e54-85a6-44b8-9716-ac753516193f.png)

**Comment by rithviknishad** [comment] 2022-11-28 09:57
Duplicate of #3992

**Closed as not planned by rithviknishad** 2022-11-28 09:57 UTC

**Comment by rithviknishad** [comment] 2022-11-28 09:58
And solved in #4118.
