### ISSUE TITLE
Number of Users under each facility

### ISSUE THREAD

**Issue by NNSiri** [coronasafe/care_fe#7509] opened 2024-04-01 09:00 UTC
**The users are mixed up when viewed**
On viewing View users feature, we are randomly seeing all the users mixed up for each facility.

**To Reproduce**

1. Go to 'Facilities - Eg Gokak '
2. Click on 'manage Facility'
3. Scroll down to 'View Users'
4. See error - 39 users are shown

1. Go to 'Users'
2. Click on 'Advance filters'
3. Scroll down to 'State: Karntaka, District : Belagavi '
4. See error: We see 11 Users for Gokak.

**Expected behavior**
Under (View Facility - Manage Facility - view users) we have to see only the users linked to that particular facility as home facility. 

**Screenshots**
 When Belagavi district is viewed

![WhatsApp Image 2024-04-01 at 14 25 23_28fc8fa2](https://github.com/coronasafe/care_fe/assets/165636597/553f4851-11a8-43f8-87f4-3b5f7d8a0896)

When Gokak facility is viewed separately
**Deskt
![WhatsApp Image 2024-04-01 at 14 24 10_4508456b](https://github.com/coronasafe/care_fe/assets/165636597/c1cf910c-2d44-4661-bcc7-6967801e7e2d)

op (please complete the following information):**

- Browser [e.g. chrome, ]

**Comment by hrit2773** [comment] 2024-04-01 12:20
@rithviknishad @NNSiri can you assign this to me

**Comment by hrit2773** [comment] 2024-04-01 18:20
@NNSiri @rithviknishad this issue should be solved from the backend side by adding extra filter field to filter it according to the home facility. This would be a better approach can you assign this to me I will make a PR and if possible you can move this issue to the care backend and assign me

**Comment by hrit2773** [comment] 2024-04-02 03:01
I can make part by part PR one in frontend and other in backend. Can you plz assign me so that I can start working

**Comment by hrit2773** [comment] 2024-04-14 11:57
@rithviknishad can I take this up?

**Comment by NNSiri** [comment] 2024-04-16 12:38
Any update on this issue ?

**Comment by hrit2773** [comment] 2024-04-16 12:53
@NNSiri I'm ready to take this up I have had a look on this issue last week. there is no filter for the users based on home facility field that needs to be added it's a frontend and backend issue waiting for a confirmation from @rithviknishad

**Comment by rithviknishad** [comment] 2024-04-16 13:03
@hrit2773 We could develop a better UX to explicitly convey to the users what is being shown, whether the listed users belong to home or linked facilities. One could interpret it differently if not mentioned.

**Comment by hrit2773** [comment] 2024-04-16 13:09
@rithviknishad let's give an option to choose whether to show all the users associated with that facility or just with home facility.. how would that be?

**Comment by rithviknishad** [comment] 2024-04-16 13:11
Works, maybe a checkbox saying "include linked facilities"

**Comment by hrit2773** [comment] 2024-04-16 13:19
@rithviknishad yes so the tasks to do would be 
1) adding a checkbox to select whether to filter based on home facility or linked facility  
2) adding a filter for home facility 
3) writing test cases

**Comment by nihal467** [comment] 2024-04-27 07:37
https://github.com/coronasafe/care_fe/pull/7685 the issue is resolved

**Closed as completed by nihal467** 2024-04-27 07:37 UTC
