### ISSUE TITLE
Patient Filter Last Admitted To (Bed Type), not working

### ISSUE THREAD

**Issue by siddnikh** [coronasafe/care_fe#4224] opened 2022-12-05 16:25 UTC
**Describe the bug**
When you apply the patient filter -Bed Type: None,
it does not work or affect the current llist of patients.

**To Reproduce**

1. Go to https://care.coronasafe.in/patients
2. Click on Advanced Filters
3. Scroll down to Last Admitted To(Bed Type) and choose any of the given options.
4. See the number of patients will be the same, unaffected.

**Screenshots**
Before applying the filter:
<img width="1680" alt="Screenshot 2022-12-05 at 9 51 23 PM" src="https://user-images.githubusercontent.com/51060067/205688627-c69fc968-d94d-4c61-86b8-78ac17ac20f7.png">

After applying the filter:
<img width="1680" alt="Screenshot 2022-12-05 at 9 51 42 PM" src="https://user-images.githubusercontent.com/51060067/205688661-656545be-8297-4f82-9e7e-0c5350b05431.png">

**P.S.** After rechecking, neither of the Last Admitted To (Bed Type) filters aren't working.

**Comment by nihal467** [comment] 2022-12-06 10:51
@siddnikh it is getting resolved in #3963 ,

**Comment by rithviknishad** [comment] 2022-12-06 12:45
Duplicate of #3953

**Closed as not planned by rithviknishad** 2022-12-06 12:45 UTC
Labels: duplicate
