### ISSUE TITLE
Heartbeat description is missing in events log

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8457] opened 2024-09-02 10:57 UTC
**Describe the bug**

Heartbeat description we added during a patient log update is missing in the events log present in the patients consultation page

**To Reproduce**

1. Go to patient tab and open any active consultation
2. click on the log update and add a rhythm description for the patient and save it
3. in the patient consultation page, on the event log
4. See the error

**Expected behavior**

Heartbeat rhythm description should be visible in the events log at the patient consultation page

**Screenshots**

![image](https://github.com/user-attachments/assets/042cce76-aec1-4aaa-82a7-d5baffca3a2b)
![image](https://github.com/user-attachments/assets/9ed65679-465d-4ab0-99f4-753df60c7878)

**Comment by HitishRaoP** [comment] 2024-09-11 12:26
@nihal467 when we submit the Log Update Form, it is logged as **rhythm_detail** but when we fetch it from the api to display in the evenlist page it is logged as **rhythm_details** and it is always null. I think this is causing the error.

During Form submission:
![Screenshot 2024-09-11 171726](https://github.com/user-attachments/assets/8cc8cc65-4455-496b-8bc0-73a15ad8418c)

Fetching from api:
![Screenshot 2024-09-11 171751](https://github.com/user-attachments/assets/5d703814-9efe-48aa-bf6d-3641e3cf0a21)

**Comment by rithviknishad** [comment] 2024-09-12 05:08
Thanks for debugging the root cause @HitishRaoP 

Looks like there's a spelling mistake in the event types. It'll have to be updated here: https://github.com/ohcnetwork/care/blob/develop/care/facility/management/commands/load_event_types.py#L123

cc: @sainak

**Comment by praffq** [comment] 2024-09-19 16:38
@rithviknishad  can you please assign this issue to me.

**Closed as completed** 2024-09-19 18:26 UTC
Labels: bug, Backend
