### ISSUE TITLE
Remove MUI on Patient Transfer form

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#5128] opened 2023-03-18 10:38 UTC
**Describe the bug**
Remove MUI components from Patient Transfer form dialog and add spacing between buttons

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient
2. Under Phone Number field enter "99999-99999"
3. On the popup select `Admit the patient record to your facility by adding the date of birth` and click `Continue`

**Screenshots**
![image](https://user-images.githubusercontent.com/70687348/226100400-4c2a9b5c-ddc7-43b9-a3e2-d2b8ebd12a24.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rithviknishad** [comment] 2023-03-18 11:35
@Pranshu1902 duplicate of #4959
make use of tasks in #5006 epic to migrate MUI components

**Closed as completed** 2023-03-18 11:46 UTC
