### ISSUE TITLE
Asset creation form text box outline are turning black instead of green

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3973] opened 2022-11-06 06:56 UTC
**Describe the bug**

in the asset creation form, after entering the asset name, and use TAB key for moving to next column, the outline of the boxes become black but at the same time, if we click it, it become green 

**To Reproduce**

https://care.coronasafe.in/facility/c4911f55-d4f7-4b36-bbcb-9b115d1bfe2c/assets/e0744026-5017-489d-9636-72379436ca1c

**Expected behavior**

we use mouse click or tab, the outline should be green

**Screenshots**

![WhatsApp Image 2022-11-06 at 11 52 20](https://user-images.githubusercontent.com/57055998/200158370-f4502d53-31fc-42e5-931a-4a2a59d5267d.jpg)

**Comment by rithviknishad** [comment] 2022-11-06 09:02
@nihal467 @khavinshankar the issue is solved and not present in #3882 as it was changed to the newer `SelectMenuV2` from `SelectMenu`

**Comment by khavinshankar** [comment] 2022-11-08 05:31
@nihal467 merging #3882 should fix it, closing this issue, feel free to reopen it if the problem persists

**Closed as completed by khavinshankar** 2022-11-08 05:31 UTC
