### ISSUE TITLE
Attribution to Doctor- when nurse edits prescription

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7656] opened 2024-04-18 11:44 UTC
**Is your feature request related to a problem? Please describe.**
Today in CARE, doctors do not always update all details for the patients themselves and offload that work on nurses. 
Nurses usually mark the suggested changes in medicines on the medicines tab.

However, legally it is mandated to keep the record of the prescription with the information on which doctor has suggested the medicines. 

**Describe the solution you'd like**

- [ ] https://care.coronasafe.in/facility/997c7f30-8e2f-4d62-8b58-2a8771e658d6/patient/d65e8b33-d631-4744-b9af-c371160288a8/consultation/04d26287-2108-4df4-95e4-11767d33fed7/prescriptions 

Only for nurse user type, add an additional field with dropdown of "list of local doctors" must be available with the text:- "Prescribed by" against each medicine entry.

Nurse must select which doctor prescribed the medicines. 

- [ ] Add the same field when the nurse tries to edit/discontinue a medicine
https://care.coronasafe.in/facility/997c7f30-8e2f-4d62-8b58-2a8771e658d6/patient/d65e8b33-d631-4744-b9af-c371160288a8/consultation/04d26287-2108-4df4-95e4-11767d33fed7/prescriptions

- [ ] When user clicks on medicine to expand information change "Prescribed 3 minutes ago by Aparna Sathianathan" to "Prescribed by Dr. XYZ and entered by ABC"
https://care.coronasafe.in/facility/997c7f30-8e2f-4d62-8b58-2a8771e658d6/patient/d65e8b33-d631-4744-b9af-c371160288a8/consultation/04d26287-2108-4df4-95e4-11767d33fed7/medicines

**Comment by vishisht-dubey** [comment] 2024-04-19 07:45
Hey @aparnacoronasafe would you please assign this to me??

**Comment by rithviknishad** [comment] 2024-04-25 13:31
@vishisht-dubey few more things:

- As for the migration, existing data can be set to null for `prescribed_by`.
- For such entries show only "entered by `<user name>`" in the FE and omit the "prescribed by `<user name>`"
- The prescribed by doctor's home facility must be the same as the patient's admitted facility.

cc: @aparnacoronasafe

**Comment by vishisht-dubey** [comment] 2024-04-26 17:21
> @vishisht-dubey few more things:
> 
> * As for the migration, existing data can be set to null for `prescribed_by`.
> * For such entries show only "entered by `<user name>`" in the FE and omit the "prescribed by `<user name>`"
> * The prescribed by doctor's home facility must be the same as the patient's admitted facility.
> 
> cc: @aparnacoronasafe

ok got it

**Comment by vishisht-dubey** [comment] 2024-04-26 18:48
@rithviknishad @aparnacoronasafe is there any api to find out the role of a logged in user.

**Comment by gigincg** [comment] 2024-08-05 01:58
@vishisht-dubey Will you be able to work on this issue?

@sainak Can you add the required clarification?

**Comment by sainak** [comment] 2024-08-05 18:03
> @rithviknishad @aparnacoronasafe is there any api to find out the role of a logged in user.

@vishisht-dubey, yes the `api/v1/users/getcurrentuser/` returns the details of the current user which includes the role

**Comment by rithviknishad** [comment] 2024-09-05 17:54
Closing as duplicate of #8492

cc: @aparnacoronasafe

**Closed as not planned by rithviknishad** 2024-09-05 17:54 UTC
Labels: Backend, Frontend
