### ISSUE TITLE
Auto-close WhatsApp Redirect Tabs to Prevent Browser Clutter in Doctor Connect Feature

### ISSUE THREAD

**Issue by Ashesh3** [coronasafe/care_fe#7239] opened 2024-02-21 07:02 UTC
#### Problem Statement:
In our application's Doctor Connect section, we have implemented a "Connect with WhatsApp" button that facilitates direct communication between doctors and patients or other doctors. This feature opens a new browser tab each time a user initiates a WhatsApp conversation using the `whatsapp://send?text=WHATSAPP_MESSAGE` protocol. Feedback from users, particularly doctors who often initiate multiple calls during their rounds, indicates that these tabs frequently remain open, leading to a cluttered and unmanageable browser environment. This not only affects the usability of our application but also hampers the overall user experience, as navigating through numerous open tabs can be cumbersome and inefficient.

#### Proposed Solution:
To address the issue of browser clutter caused by unused tabs, we propose implementing an auto-close functionality for tabs opened by the "Connect with WhatsApp" action. Specifically, a tab would automatically close one minute after it has been opened. This approach leverages the fact that our application has permission to close windows it has opened, allowing for a cleaner and more manageable browser workspace for our users. 

#### Implementation Considerations:
- **User Experience:** Ensure the auto-close functionality does not disrupt the user's workflow, especially if they are still actively using the WhatsApp tab.
- **Permissions:** Verify that our application's current permissions indeed allow for this behavior across all targeted browsers and devices.
- **Fallback Strategy:** In case the auto-close feature cannot be implemented universally due to browser limitations or permissions, consider alternative solutions to minimize browser clutter, such as prompting users to close the tab manually after the WhatsApp action is completed.

#### Request for Feedback:
We invite feedback from the development team, UI/UX designers, and other stakeholders on the proposed solution. Specifically, insights on potential edge cases, user experience implications, and technical feasibility would be invaluable. Additionally, suggestions for alternative approaches to address the issue are welcome.

**Comment by Ashutosh0602** [comment] 2024-02-23 15:10
Hey, I was looking over the solution for this and find out closing tab after one minute will not have good UX. 
It will be better to close the tab if it is not in 'Active' state.

**Comment by Ashutosh0602** [comment] 2024-02-23 15:11
If I assigned over this issue, I can work on the code part.

**Comment by Ashesh3** [comment] 2024-02-23 15:18
Hey, checking for the active state is a good idea! Before working on this issue let's first discuss this on monday's EOD call then I will let you know what we have planned for this.

**Comment by Thanush19** [comment] 2024-03-07 23:57
Hey, if the issue is not completed, I can work on this., @Ashesh3

**Closed as completed** 2024-03-19 11:34 UTC
