### ISSUE TITLE
make buttons stick to bottom on facilities page

### ISSUE THREAD

**Issue by Ritesh-Aggarwal** [coronasafe/care_fe#4075] opened 2022-11-18 10:25 UTC
**Describe the bug**
<img width="905" alt="image" src="https://user-images.githubusercontent.com/57039447/202680207-65b05728-406f-4cee-9bb8-79b5df01e8da.png">

**To Reproduce**
go to https://care.coronasafe.in/facility

**Expected behavior**
Buttons should stay at bottom of the card

**Comment by rithviknishad** [comment] 2022-11-18 10:40
@Ritesh-Aggarwal duplicate of #3954 and #4012 and resolved in #3959

**Closed as completed by rithviknishad** 2022-11-18 10:40 UTC
Labels: duplicate
