### ISSUE TITLE
Back Button is not working Properly 🐞🐞🐞🐞

### ISSUE THREAD

**Issue by mdaatifayman786** [coronasafe/care_fe#9236] opened 2024-11-28 18:05 UTC
**Describe the bug**
Navigate to Camera Configuration through camera feed. On the configuration page back button is not working properly.

**To Reproduce**

1. Go to 'https://care.ohc.network)https://care.ohc.network/
2. Login with devdistrictadmin credentials
3. Navigate to Patient named 'Gigin'
4. Click on Feed Tab (alternatively, direct link to the feed page: https://care.ohc.network/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/edfe0bd6-0f50-4a4c-8cd0-2d4ad0e9cea1/feed
5. Click on info button on the top right near dev camera
6. Then click on configure button
7. In configure page click on back button. it is not navigating to previous camera feed.

**Expected behavior**
When I click on the back button, it should return to my camera feed page.

**Screenshots**
https://github.com/user-attachments/assets/1b8484c5-cbe2-45e0-a896-c1f29cd87ce5

**Desktop (please complete the following information):**

- OS: [WIndows]
- Browser [chrome]

**Comment by rithviknishad** [comment] 2024-11-28 18:08
Duplicate of #9233

**Closed as not planned** 2024-11-28 18:07 UTC
