### ISSUE TITLE
Design Enhancement for Bed Management

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6974] opened 2024-01-04 17:12 UTC
We have recently redesigned the Location Management. It'd be nice to have a similar design for Bed Management too.

Current:
<img width="2321" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/7597aec6-38f6-4794-b759-f915590ef85d">

Expected:
<img width="2290" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/afe47c0f-d2ef-4973-9c6f-3439f173fcac">

**Comment by 2008sahil** [comment] 2024-01-06 10:40
can you please assign it to me .

**Comment by pred695** [comment] 2024-01-12 11:40
Hello @rithviknishad , can you please assign this issue to me? I can see to if I can make a good design corresponding to the one in location management.

**Comment by abdulhasibn** [comment] 2024-01-21 02:09
@rithviknishad .  I would like contribute to this. How can I start the process ?

**Comment by parthksingh1** [comment] 2024-02-21 18:23
hi @rithviknishad, can you please assign me this issue

**Comment by Thanush19** [comment] 2024-03-08 00:01
Hey, if the issue is not completed, I can work on this. @rithviknishad

**Comment by Thanush19** [comment] 2024-03-11 09:14
@rithviknishad , how can i reproduce this ? ...

**Comment by rithviknishad** [comment] 2024-03-11 09:16
Hey, you can open up a facility and in Manage Facility, you can open up Location Management.

In each of those locations, there'd be an option to click "Manage Beds"

**Comment by Thanush19** [comment] 2024-03-11 15:16
![image](https://github.com/coronasafe/care_fe/assets/110150744/96091af0-09d4-4e77-a6f2-0ad0436dff4c)
hey @rithviknishad , is this layout is fine??

**Comment by Thanush19** [comment] 2024-03-12 07:47
hey @rithviknishad 

![image](https://github.com/coronasafe/care_fe/assets/110150744/0d3b8681-8a2d-4e19-b0de-83fb4596a32a)
![image](https://github.com/coronasafe/care_fe/assets/110150744/97d8d8a5-968b-49b1-b86f-3fabac822833)

Is the layout for bed management satisfactory? Please let me know if there are any adjustments needed.

**Comment by Thanush19** [comment] 2024-03-13 07:51
hey @rithviknishad , kindly review the PR #7399

**Comment by Thanush19** [comment] 2024-03-18 03:41
hey @rithviknishad , whats the status in my PR , is there any changes required???

**Comment by nihal467** [comment] 2024-04-27 07:14
@Thanush19 Unassigning you from this issue due to inactivity. Feel free to reassign yourself if you are still working on it.

**Comment by gnanasurya2** [comment] 2024-06-20 15:15
@rithviknishad @nihal467 Please assing this issue to me
I have created a PR for this [8073](https://github.com/coronasafe/care_fe/pull/8073)

**Comment by Jacobjeevan** [comment] 2024-10-18 13:18
The cards might seem a bit empty 🤔 for ones without description. Any opinions?

@rithviknishad 

![Image](https://github.com/user-attachments/assets/c4ab70a5-fe62-439f-a256-5dee03381179)

**Comment by rithviknishad** [comment] 2024-10-18 13:25
We could truncate it to 1 line with ellipsis maybe. 

Is description useful for a bed? cc: @bodhish

**Comment by bodhish** [comment] 2024-10-19 01:54
Truncate after 2 lines

**Closed as completed** 2024-10-22 16:09 UTC
Labels: good first issue, hacktoberfest, UI-Enhancement
