### ISSUE TITLE
Pressure sore : width and height units are missing

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8209] opened 2024-07-24 09:59 UTC
**Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]](https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/edfe0bd6-0f50-4a4c-8cd0-2d4ad0e9cea1/daily_rounds/9ad27d33-0ced-4c11-9274-90cf8f86b316/update)

When marking push score (a scoring mechanism to understand how bad the sore is) for pressure sores , the width and high of the pressure sores are measured and logged in cms.

The form in CARE fails to mention the unit of measurement

**Describe the solution you'd like**
![Screenshot 2024-07-24 at 3 26 42 PM](https://github.com/user-attachments/assets/f9f9ad20-49a5-4247-b6ab-152b9aa927f5)
Add unit as cm

**Comment by Bikram-ghuku** [comment] 2024-07-27 06:55
Can I work on this?

**Comment by kushalbhana** [comment] 2024-08-03 16:22
How can I reproduce same issue

**Comment by nihal467** [comment] 2024-08-04 12:17
@kushalbhana 



> How can I reproduce same issue

1. Login to the platform
2. click on the patient tab in the sidebar
3. from the list of patient cards, select any one patient with a consultation
4. once you are on the patient consultation page, click on the manage patient button,
5. from the dropdown, select edit consultation
6. in the consultation page, check for the weight and height page

**Comment by nihal467** [comment] 2024-08-04 12:17
@kushalbhana the issue is already assigned to @Bikram-ghuku , feel free to take up any other open issues

**Comment by ahmedobaid23** [comment] 2024-08-08 11:17
@nihal467 
I don't see any weight and height page here. Can you guide me where exactly is the issue?
![image](https://github.com/user-attachments/assets/0361e6b5-ea45-4fb5-b4d1-31d5724af0fc)

**Comment by nihal467** [comment] 2024-08-08 11:33
> @nihal467 I don't see any weight and height page here. Can you guide me where exactly is the issue? ![image](https://private-user-images.githubusercontent.com/111188459/356197600-0361e6b5-ea45-4fb5-b4d1-31d5724af0fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTY3NzgsIm5iZiI6MTcyMzExNjQ3OCwicGF0aCI6Ii8xMTExODg0NTkvMzU2MTk3NjAwLTAzNjFlNmI1LWVhNDUtNGZiNS1iNGQxLTMxZDU3MjRhZjBmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTI3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWZkMWUwMTI4NWY2NjI3NDg5MTc5MzgxMWM3MWVlMGUyM2RjZWI2NThjNDcwNzhmMmQ0OTA0OTc4YjQwZmIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aC5tiiJ3NNo57KuWSz2RCEMbKL-VXYT6AQBSQsAjBAI)

@ahmedobaid23 sorry, for the incorrect steps you can use the below steps

1. Login to the platform
2. click on the patient tab in the sidebar
3. from the list of patient cards, select any one patient with a consultation
4. once you are on the patient consultation page, click on log update
5. in the log update page, select Detailed Update in the round type dropdown and fill all necessary mandatory field with random values
6. then click the save button, once you are on the record updates page, click on the pressure sore section
7. once you are in the pressure sore section, click on any of the human anatomy part
8. you will see the error, units are missing for height and weight fields in the pop-up

**Comment by Bikram-ghuku** [comment] 2024-08-08 12:13
I am unassigning myself as I am unable to work on this...

**Comment by Fredrick2503** [comment] 2024-08-10 12:04
I would like to work on this issues.

**Comment by himanshu-sharmav** [comment] 2024-09-19 00:01
Hello @nihal467 I would like to work on this issue, can you please assign this to me?

**Comment by rithviknishad** [comment] 2024-09-30 12:29
@himanshu-sharmav unassigning due to inactivity. Feel free to assign again and create a draft PR or ask questions if stuck on understanding something.

**Comment by noufalrahim** [comment] 2024-09-30 17:54
@rithviknishad can u assign this to me...?

**Closed as completed** 2024-10-13 00:23 UTC
Labels: good first issue, hacktoberfest
