### ISSUE TITLE
Sign up page for authenticate a new user

### ISSUE THREAD

**Issue by Tanuj1718** [coronasafe/care_fe#9140] opened 2024-11-16 11:21 UTC
**Is your feature request related to a problem? Please describe.**
There is no option for sign in. The contributor/user might get frustrated for this as he/she don't how to do authorized login without username and password.

**Describe the solution you'd like**
There should be a Sign-in form for user in this page [https://care.ohc.network/](url) or there should be clear instructions regarding this.

**Describe alternatives you've considered**
If the login is not for everyone, then there should be clear instructions regarding this in some file.

**Comment by Tanuj1718** [comment] 2024-11-16 11:23
@nihal467 I would like to work on this, if this issue is approved.

**Comment by rohitlingarker** [comment] 2024-11-16 11:36
@Tanuj1718 There are user credentials for 3 roles (district-admin, doctor and staff) are clearly mentioned in the readme file of this repository.

**Comment by rithviknishad** [comment] 2024-11-16 12:10
duplicate of https://github.com/ohcnetwork/care_fe/issues/5710; it'd be great to search for issues already opened in the past when opening a new one.

**Closed as not planned by rithviknishad** 2024-11-16 12:10 UTC

**Comment by Tanuj1718** [comment] 2024-11-16 17:21
@rithviknishad Oh sorry! Will keep it in mind from the next time.
