### ISSUE TITLE
Search Field Loses Focus After Typing and Search Operation on User Page.

### ISSUE THREAD

**Issue by i0am0arunava** [coronasafe/care_fe#9533] opened 2024-12-23 05:53 UTC
**Describe the bug**
Search Field Loses Focus After Typing and Search Operation on User Page.

**To Reproduce**

1. Go to the user page.(https://care.ohc.network/users)
2. Type anything inside the search field.
3. Wait for the search operation to complete.
4. After the search operation, the component re-renders and the focus is lost from the search field.

**Expected behavior**
After completing the search operation, the search field should retain focus, allowing the user to continue typing or make adjustments without needing to click back into the field.

**Screenshots**
https://github.com/user-attachments/assets/99eb290d-ca34-47f1-9eab-35efa475a6ca

**Desktop (please complete the following information):**

- OS: windows 11
- Browser chrome
- Version - latest

**Comment by i0am0arunava** [comment] 2024-12-23 05:53
I would like to work on this @nihal467 @rithviknishad

**Comment by AdityaJ2305** [comment] 2024-12-23 05:55
Duplicate of https://github.com/ohcnetwork/care_fe/issues/9398

**Closed as duplicate** 2024-12-23 05:57 UTC
