### ISSUE TITLE
improve display of icons

### ISSUE THREAD

**Issue by SwanandBhuskute** [coronasafe/care_fe#9460] opened 2024-12-16 15:04 UTC
**Describe the bug**
CSS bugs on these two pages
- consultation form Symptoms area
- assets configure area

- need to readjust the "calendar" icon and "down arrow" icon to center
- need to avoid overlapping of text over "eye" icon inside "Password" and "Stream UUID"

**To Reproduce**
1. go to consultation form for any patient
2. go to /configure of camera asset

**Expected behavior**
Proper CSS implemented display content rightly

**Screenshots**
![Image](https://github.com/user-attachments/assets/e5ff0156-c1eb-409b-b5a8-2a958d34f13d)
![Image](https://github.com/user-attachments/assets/c3a0be50-a7d6-48a2-a522-1d51e7c5ed0b)

**Desktop (please complete the following information):**

- OS: Windows
- Browser - chrome
- Version - latest

**Additional context**

**Comment by Tanuj1718** [comment] 2024-12-16 15:07
@rithviknishad  Please assign it to me. Would like to work on this.

**Comment by rithviknishad** [comment] 2024-12-16 17:08
Duplicate of #8998 and #9465

**Closed as duplicate by rithviknishad** 2024-12-16 17:08 UTC
