### ISSUE TITLE
Using saved passwords overlays on the placeholder text in authorized login page 

### ISSUE THREAD

**Issue by Pragati1610** [coronasafe/care_fe#4111] opened 2022-11-25 05:28 UTC
![Screenshot from 2022-11-25 10-56-48](https://user-images.githubusercontent.com/55177805/203907412-1519e8ce-b79b-43f9-8449-30cf9f0dbb29.png)

**Comment by rithviknishad** [comment] 2022-11-25 08:28
Duplicate of https://github.com/coronasafe/care_fe/issues/3992

**Closed as not planned by rithviknishad** 2022-11-25 08:28 UTC
