### ISSUE TITLE
 Error message on clicking patient Card (User Type: Pharmacist)

### ISSUE THREAD

**Issue by Sunilsubba** [coronasafe/care_fe#7158] opened 2024-02-02 12:10 UTC
**Describe the bug**
An error message is coming up when clicking on the patient card to view the patient dashboard.

**To Reproduce**
1. Login with provided credential
2. Go to Patient
3. Click on any Patient Card
4. Error: _"You don't have permission to perform this action."_

**Login Credential**
Username: pharmacist_123
Password: Lilo@123

** Expected Behavior**
Pharmacists are allowed to view the patient details but not edit them. So, an error message should only come up when they try to update something on patient details.

**Screenshots**
![Screenshot (15)](https://github.com/coronasafe/care_fe/assets/144016088/d8f8e7bf-876b-4b07-a709-420f7b37ca32)
![Screenshot (16)](https://github.com/coronasafe/care_fe/assets/144016088/ed13fe87-aebd-46dc-95cb-764c8d210dad)

**Comment by sainak** [comment] 2024-02-02 12:18
seems like acces control restricton from the backend 
@aparnacoronasafe can you update [this](https://github.com/coronasafe/care_fe/issues/6240#issuecomment-1783827403) table with pharmacist and other roles

**Comment by aparnacoronasafe** [comment] 2024-02-15 08:27
@sainak 

Please find the updated user access in the required format here: https://docs.google.com/spreadsheets/d/1HFmwBbbzQfeBy6fHkIbeNhrncil6c8fR8xmn7SIw9sU/edit?usp=sharing

**Comment by kabirrajsingh** [comment] 2024-03-26 14:26
Hi. Is this issue still relevant?
@aparnacoronasafe @gigincg

**Comment by gigincg** [comment] 2024-03-28 17:26
@nihal467 Can you comment on the relevance of this

cc: @kabirrajsingh

**Comment by nihal467** [comment] 2024-04-27 07:54
@kabirrajsingh the issue is still relevant, the modified user access is attached in the sheet

**Comment by Mahendar0701** [comment] 2024-12-30 16:53
@nihal467 , @rithviknishad @Jacobjeevan  i want to work on this. Please assign this to me

**Comment by Jacobjeevan** [comment] 2024-12-30 17:02
> @nihal467 , @rithviknishad @Jacobjeevan  i want to work on this. Please assign this to me

All of this is being redone in `form-field-v1`, so closing it.

**Closed as not planned** 2024-12-30 17:03 UTC
