### ISSUE TITLE
Redirect not working upon login

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6900] opened 2023-12-24 02:10 UTC
**Describe the bug**
If a user is logged out and they go to a specific URL directly, they are not landing on that URL after login.

**To Reproduce**

1. Ensure you are logged out
2. Visit https://care.ohc.network/facility/ea9a2fbe-74f3-446b-bdb0-e038766bfb09/cns?page=1&limit=6
3. Enter credentials
4. Expected: "CNS Page of a Facility", Got: "Facilities List Page"

## Tasks
- [x] The user should be redirected to the specific URL when logged in.
- [x] Write Cypress Test to test this behaviour.

**Comment by AshrafMd-1** [comment] 2023-12-24 06:01
I want to work on this issue can u assign me this?

**Comment by Om-Thorat** [comment] 2023-12-25 11:02
@rithviknishad Can you assign this to me?

```tsx
const getRedirectURL = () => {
  return new URLSearchParams(window.location.search).get("redirect");
};
```

The problem is probably the getRedirectURL function which always returns null

**Comment by Om-Thorat** [comment] 2023-12-25 11:15
@rithviknishad  This is a code design decision seems like the component expects an extra ?redirect= param at the end of string to redirect to, This isn't needed since the login page is shown on the same url that the user intends to go to. One way would be to redirect to the login page with a redirect param or another easier way might be to just use current url and just redirect to that after login.

**Comment by rithviknishad** [comment] 2023-12-25 11:38
The second approach sounds good!

**Comment by Om-Thorat** [comment] 2023-12-25 11:44
Great! I'll get to it

**Closed as completed** 2024-02-28 04:13 UTC
Labels: bug
