### ISSUE TITLE
Reduce grid columns for patients page on smaller screens

### ISSUE THREAD

**Issue by shivankacker** [coronasafe/care_fe#3990] opened 2022-11-07 09:35 UTC
![image](https://user-images.githubusercontent.com/23238460/200276688-4885ed7e-7d85-4357-87e8-aea676a5b5f6.png)

**Comment by rithviknishad** [comment] 2022-11-07 09:37
@skks1212 duplicate of #3966

**Closed as not planned** 2022-11-07 09:50 UTC
