### ISSUE TITLE
Dropdown collapse when no data for local body

### ISSUE THREAD

**Issue by mohanrajnambe** [coronasafe/care_fe#7355] opened 2024-03-07 06:01 UTC
**Describe the bug**
When a district is chosen and an empty array is received as response for the local body, the local body dropdown is neither disabled nor showing no option in it.
no intimation to the user and the option value dropdown renders in a collapsed way.

**To Reproduce**
1. Create a new patient. 
2. select 'Tamil Nadu' option in State
3. Choose districts like Chennai, Ariyalur 

**Expected behavior**
Local body dropdown should show no option available in dropdown
<img width="598" alt="image" src="https://github.com/coronasafe/care_fe/assets/55721773/57074bf7-9b3d-43cc-8018-c468e145eafc">

**Screenshots**
<img width="598" alt="image" src="https://github.com/coronasafe/care_fe/assets/55721773/3d9b967e-0b49-4e00-9885-79495ca5fd1e">

**Comment by mohanrajnambe** [comment] 2024-03-07 06:06
@rithviknishad Can you please assign this to me? Also, please let me know your thoughts on the issue

**Comment by r-nikhilkumar** [comment] 2024-03-07 11:17
@mohanrajnambe, Can you please assign this issue to me?

**Comment by r-nikhilkumar** [comment] 2024-03-07 11:20
@rithviknishad, can you assign this issue to me?

**Comment by rithviknishad** [comment] 2024-03-07 11:31
But local body is a mandatory field right.

**Comment by mohanrajnambe** [comment] 2024-03-07 12:33
Yes, it is. Looks like there exists some districts without local bodies where the no option case is not handled in the dropdown

**Comment by mohanrajnambe** [comment] 2024-03-07 15:44
@rithviknishad @aparnacoronasafe 
I would like to propose two solutions for this
Solution 1: disable the select when the result option array is empty and show the placeholder of 'No option available'. Also, handle the option length logic in the select component. so that Listbox.Options will not be rendered if empty array is passed for options. 
Solution 2: In the SelectMenuV2 component, do a check for the options array length and render the ListBox.Options with passed values when it is not empty and show 'No option found' disabled option in the ListBox when it is empty. 

Let me know your thoughts on this.

**Comment by rithviknishad** [comment] 2024-03-07 15:49
Would you be able to submit the form in the first place without a local body?

cc: @nihal467

**Comment by mohanrajnambe** [comment] 2024-03-07 15:55
No, the form will not be submitted.  The logical validation is present.
What I am mentioning here is the UI ambiguity on the dropdown which is not handling the 'no options' scenario

**Comment by Thanush19** [comment] 2024-03-08 00:17
Hey, if the issue is not completed, I can work on this.

**Comment by Thanush19** [comment] 2024-03-08 00:17
@mohanrajnambe

**Comment by rithviknishad** [comment] 2024-03-08 04:50
> No, the form will not be submitted. The logical validation is present. What I am mentioning here is the UI ambiguity on the dropdown which is not handling the 'no options' scenario

@mohanrajnambe Alright. Yes, I think we can disable the select menu and override the placeholder with "No options available"

**Closed as completed** 2024-04-02 13:45 UTC
