### ISSUE TITLE
Content overflow in Discussion Notes

### ISSUE THREAD

**Issue by nithish1018** [coronasafe/care_fe#8965] opened 2024-10-30 07:15 UTC
**Describe the bug**
The notes contents are overflowing over **Doctor's Discussion** and **Nurses's Discussion** tabs in full screen mode of discussion notes

**To Reproduce**

1. Go to '/patients'
2. Select any patient who doesn't have **unknown tab**
3. Select Discussion Notes and open that in full screen in mode
4. Now slowly scroll through the content and see the error

**Screenshots**

![Image](https://github.com/user-attachments/assets/714645d1-d128-40bc-8b56-33896fef155a)

https://github.com/user-attachments/assets/aaaaed34-fea6-4356-9baa-16b8f1fb0fc3

**Desktop**

- OS: Windows
- Browser Chrome
- Version Latest

**Comment by nithish1018** [comment] 2024-10-30 07:16
I'd like to work on this issue.
@rithviknishad @Jacobjeevan

**Comment by rithviknishad** [comment] 2024-11-02 07:42
Closing as duplicate of #8795

**Closed as not planned by rithviknishad** 2024-11-02 07:42 UTC
