### ISSUE TITLE
Patient transfer

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7120] opened 2024-01-30 11:20 UTC
**Describe the bug**
When a patient who has "Transfer allowed" on the profile, when the file is pulled into another facility, the encounter is not closed in the previous facility.

**To Reproduce**

1. Go to any patient profile (Patient A) and "Allow transfer"
2. Go to any facility and Click on 'Add patient'
3. Type in Patient A's phone number is the patient registration form
4. A pop-up to pull the patient record appears. Input the patient A's DOB. 
5. The patient card gets transferred to the new facility.
6. Try filing a consultation for the patient. An error appears saying a consultation already exists.
7. Any log update filed on the patient actually gets logged on the last hospital records.

**Expected behavior**
Allow pulling of patient records only for discharged patients. If it is a live patient in another facility, show an error saying "the patient's record is Live in XYZ facility. Kindly contact the Nodal person of the facility at "Emergency contact no. for the facility" to transfer the patient file"

@gigincg please review

**Comment by Ashesh3** [comment] 2024-02-18 21:02
@aparnacoronasafe I am unable to replicate this. When i repeat the above steps, the old consultation correctly gets auto-closed, and a new consultation is filed at the destination facility.
@nihal467 could you confirm if we still have this issue?

**Comment by Ashesh3** [comment] 2024-02-21 06:42
@aparnacoronasafe @nihal467 is this issue still happening? I am not able to reproduce this issue with the steps given. The old consultation correctly gets auto closed.

**Comment by Ashesh3** [comment] 2024-03-06 12:18
Closing this issue as non-reproducible. Please feel free to reopen it if the problem persists.

**Closed as not planned by Ashesh3** 2024-03-06 12:18 UTC
