### ISSUE TITLE
Bug: Unable to select any other date when trying to administer the prescription in past

### ISSUE THREAD

**Issue by aeswibon** [coronasafe/care_fe#7439] opened 2024-03-19 14:09 UTC
**Describe the bug**
When I try to select a previous date, I cannot select it.

**To Reproduce**

1. Go to [Patient's Prescription manage page](https://care.ohc.network/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/edfe0bd6-0f50-4a4c-8cd0-2d4ad0e9cea1/prescriptions)
2. Click on the `Administer` button and select `Administer for a time in the past` checkbox
3. Now try to select a previous date using the calendar.

**Expected behavior**
Should be able to select a previous date

**Screenshots**

https://github.com/coronasafe/care_fe/assets/77210185/586489ef-0b7b-48e0-8e34-e58737317e8f

**Desktop (please complete the following information):**
- Browser: Firefox

cc: @rithviknishad

**Comment by saloni0419** [comment] 2024-03-19 15:29
@aeswibon @rithviknishad can you please assign this issue to me

**Comment by rithviknishad** [comment] 2024-03-19 16:20
@aeswibon this is intentional and not a bug. The minimum selectable date/time cannot be before the date and time of creation of the prescription.

Feel free to re-open if it is behaving differently than this. Unable to reproduce the issue.

**Closed as not planned by rithviknishad** 2024-03-19 16:20 UTC
Labels: bug
