### ISSUE TITLE
Symptoms onset date filter is not filtering as expected

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#8467] opened 2024-09-03 07:43 UTC
**Describe the bug**

The symptoms onset date filter is not filtering as expected in the patient advance filters

Note: The entire concept of symptom onset has changed. Previously, all symptoms had a single onset date. Now, with the symptoms module update, each symptom has its own onset and cure date. We need to reconsider whether the filter should be individual symptom onset specific or remain a general onset filter.

**To Reproduce**

1. Go to Patients list page
2. Apply symptoms onset date range filter

**Expected behavior**

To be discussed

**Screenshots**
<img width="1822" alt="image" src="https://github.com/user-attachments/assets/c104ebd6-a509-48ca-ad8a-6af2af1a02d2">

**Comment by nihal467** [comment] 2024-09-05 14:14
@rithviknishad the issue is being assigned to @aparnacoronasafe to provide the expected behavior after understanding the use case

_Note: 05/09/2024 telephonic confirmation have been taken to remove existing onset filter from the frontend_

**Closed as completed** 2024-09-09 07:39 UTC
