### ISSUE TITLE
Add Minimum quantity data in the inventory list page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6612] opened 2023-11-15 08:34 UTC
**Describe the bug**
Follow-up : coronasafe/care_fe#2549 

Currently, without going to the minimum required section, we can't understand what is the minimum quantity required for the item, which is not a good user experience

**To Reproduce**

1. Go to facility inventory management page and add a item
2. See error

**Expected behavior**

On the right side on a inventory item quantity , we should be displaying the minimum quantity required

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/bd3a7c5e-6ec0-47a0-a113-be5b5d4edc6b)

**Comment by vasudevravula** [comment] 2023-11-17 04:39
Hi @nihal467 @rithviknishad 
Looked into this a bit, we need to do a getMinInventory call that is being done when the Minimum Quantity Required button is clicked to add this new column.

Also, there are two min_quantity fields in the payload, that is not so intutitve, one I assume is a default value and the other is the value set
![image](https://github.com/coronasafe/care_fe/assets/34686116/696c6ea8-eac5-402a-abb4-e74bf71ed39c)

**Comment by vasudevravula** [comment] 2023-11-17 04:43
let me know if you are okay with adding this min_quantity call during the page load, I can add this

**Comment by rithviknishad** [comment] 2023-11-17 04:45
Yup! That should be fine for now.

**Comment by vasudevravula** [comment] 2023-11-17 18:53
Can you assign this to me, I can start working on this

**Comment by vasudevravula** [comment] 2023-11-20 04:47
@rithviknishad @nihal467 I have taken a deeper look into this, and I can confirm that this needs to be fixed on the API side by adding a new property (ex: configuredMinQuantity) to the inventorysummery response that gives the minimum quantity required for each item. 
Reason: The invertorysummery API response and the min_quantity API response are both paginated. When the min_quantity list grows bigger there will be a scenario where all the items from invertorysummery might not get their corresponding min_quantity from the min_quantity list, which will lead to displaying the incorrect min quantity on the UI.

As API is already returning an is_low indicator, this shouldn't be a big change on the API side, once that is added, we can come back and fix this on the UI

**Comment by vasudevravula** [comment] 2023-11-20 04:49
I'm happy to make this change on the API side and then come back and fix this. If you're okay with it, please create an issue on the API repo and assign it to me and link this issue there

**Comment by vasudevravula** [comment] 2023-11-20 13:57
@rithviknishad any thoughts on this?

**Comment by rithviknishad** [comment] 2023-11-20 14:48
@vasudevravula issue has been created. https://github.com/coronasafe/care/issues/1721

**Comment by balaji-sivasakthi** [comment] 2024-02-26 19:40
@nihal467 I would like to work on this issue.

**Comment by Thanush19** [comment] 2024-03-08 00:03
Hey, if the issue is not completed, I can work on this.

**Comment by rithviknishad** [comment] 2024-03-08 04:52
A rework of the entire inventory management is happening in coronasafe/docs#38 

cc: @khavinshankar

**Closed as not planned by rithviknishad** 2024-03-08 04:52 UTC
Labels: blocked, Backend, Frontend
