### ISSUE TITLE
Cache only the advance filters across the platform

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6891] opened 2023-12-21 11:48 UTC
**Describe the bug**

Currently the search across the platform cache all type of filters

**To Reproduce**

1. Go to any tab with search
2. See error

**Expected behavior**

we should be only cache the advance filters across the platform

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/f96c4291-020b-493f-9157-cda9b4d68e7c)

**Comment by AshrafMd-1** [comment] 2023-12-26 07:40
I want to work on this issue can you assign me this issue

**Comment by AshrafMd-1** [comment] 2023-12-26 18:25
@nihal467 small doubt 

---
Clear the cache as in `local storage`
![image](https://github.com/coronasafe/care_fe/assets/98876115/484a0322-34e7-41cf-9d5a-a9085abb7844)


---
or the auto-fill one 
![image](https://github.com/coronasafe/care_fe/assets/98876115/94e61290-cbbf-477c-a365-9211e51c4129)

**Comment by Ashesh3** [comment] 2023-12-29 05:31
@AshrafMd-1 Cache, in the sense if you search a query and then search for the same query again, it won't perform the search again. It checks if the search field has changed or not before performing a search. The issue is about removing this behavior from search inputs and keep it (as it already is) for advanced filters.

Demo:
Go here:
![image](https://github.com/coronasafe/care_fe/assets/3626859/07915154-fa05-4251-a36f-f7dee99b3341)
Press enter, then keep pressing enter to search. you will notice that it won't perform any searches since the query isn't changing, but we expect it to refetch the results from the query even if the search term is the same.

- So do not cache it in localstorage and force it to fetch results whenever we search for anything (even if the query is the same consecutively)

**Comment by AshrafMd-1** [comment] 2023-12-29 05:45
@Ashesh3 okay 
Thx for clarifying.

**Comment by AshrafMd-1** [comment] 2024-01-02 09:33
@rithviknishad can u assign this to me

**Comment by rithviknishad** [comment] 2024-01-02 17:52
We are hardocding a blacklist keys as an array as of now (for page limit offset). 

We could pass additional blacklist field keys as an array to the caching code. So that in patient list page, we can also include phone number and ip/op number fields too easily.

**Closed as completed** 2024-01-17 12:39 UTC
