### ISSUE TITLE
Redesign create asset modal

### ISSUE THREAD

**Issue by Sagarjari01** [coronasafe/care_fe#7341] opened 2024-03-05 12:51 UTC
**Describe the bug**
The current UI for the Create Assets modal has some CSS overflow issues. We can redesign the whole modal, like the tailwind CSS search, and make a reusable component to use across the app.

**To Reproduce**

1. Go to Assets.
2. Click on the Create Asset button.
3. Type any letter.
4. A scrollbar will appear on the whole page while a suggestion appears.

**Bug** 
https://github.com/coronasafe/care_fe/assets/70434968/a435fdf4-c3ff-432b-95ea-1b6d0f77f21e

**Expected behavior**
https://github.com/coronasafe/care_fe/assets/70434968/d34304db-ad00-462b-84a0-91661a935a85

**Comment by rithviknishad** [comment] 2024-03-05 12:56
@Sagarjari01 make it as a reusable component under CareUI so that it can be used in other places.

**Comment by Thanush19** [comment] 2024-03-10 11:46
hey @rithviknishad , if the issue is not resolved , i can fix this....

**Comment by kshitijv256** [comment] 2024-03-19 10:01
I can work on this issue

**Comment by MjStar24** [comment] 2024-03-19 18:14
hey @rithviknishad I would work on this can you assign this to me

**Comment by MjStar24** [comment] 2024-03-21 17:38
Hi @rithviknishad, I have a few questions. I'm aiming to create a reusable dialogue box similar to the one demonstrated in the video. Could you provide more details on what exactly I need to develop?

**Comment by MjStar24** [comment] 2024-03-24 07:08
Hi @rithviknishad, I've addressed the CSS overflow problem and transformed it into a reusable component.
Could you review it and suggest any necessary changes?

https://github.com/coronasafe/care_fe/assets/118470362/8b3e03bf-aec0-4e04-bc97-bda35472628b

**Closed as not planned** 2024-05-06 11:20 UTC
