### ISSUE TITLE
Enhancement to MEWS Score

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7373] opened 2024-03-11 06:34 UTC
**Is your feature request related to a problem? Please describe.**
Currently, for MEWS Score to be calculated all 5 data points need to be entered in the patient records through a single log update.
The 5 data points required to calculate MEWS are:
<img width="606" alt="MEWS" src="https://github.com/coronasafe/care_fe/assets/67050716/ab5b250f-a6d5-4e77-af77-90c82f1916c1">

All the above parameters other than Consciousness level, are auto-updated in CARE through BPL 5-para integration through virtual nursing assistant. if the nurse is allowed to update only consciousness level additionally, MEWS can be calculated. However, with the way the feature is developed right now, because all data points needs to be entered in a single log update, this is not possible. 

**Describe the solution you'd like**

- [ ] Allow calculation of MEWS score by fetching the relevant 5 data points spread across multiple log updates filed within a time frame of 30 min. 

Eg: 
Resp rate - updated at 10AM
Heart Rate- updated at 10AM
Systolic BP- updated at 10:15AM
Temp- updated at 10:15AM
Consciousness- updated at 10:29AM

In this case- MEWS will be calculated based on the 5 parameters, since they are all updated within a time frame of 30 min (10-10:29AM)

Subsequently if
Resp rate - revised at 10:35 AM
Heart Rate- updated at 10:35 AM

MEWS will be revised based on the entries made between 10:15AM to 10:45AM since 2/5 parameters are revised, and the 5 parameters are entered in the time frame of 30 min (10:15AM to 10:45AM)

However, later on if Systolic BP is revised again at 11:45AM, MEWS will not be revised since, only 1 parameters is updated and remaining 4 parametrers are not available within 30 min bracket.

- [ ] Add measured at time under the MEWS on Patient dashboard. mention the time stamp of the latest of the 5-parameters.

**Comment by Thanush19** [comment] 2024-03-11 08:36
@aparnacoronasafe , can i work on this..?

**Comment by hrit2773** [comment] 2024-03-12 10:58
@aparnacoronasafe can you assign this to me and tell me under which section the issue is and what are the login credentials

**Comment by r-nikhilkumar** [comment] 2024-03-13 03:51
@rithviknishad, @aparnacoronasafe can you please assign this issue to me?

**Comment by rithviknishad** [comment] 2024-04-16 13:05
Waiting for confirmation: https://github.com/coronasafe/care/pull/1991#pullrequestreview-1999055202

**Comment by nihal467** [comment] 2024-05-14 09:57
@r-nikhilkumar closing this PR and unassigning you from this issue due to inactivity, feel free to reopen the same if you are still working on it

**Comment by r-nikhilkumar** [comment] 2024-05-14 10:37
@nihal467 I worked on it already, but as per call, it was said that mews score will be implemented differently from your side that's why I didn't interacted

**Comment by rithviknishad** [comment] 2024-08-19 09:49
Update: Now that we have events, we can use the events API to fetch the last data points of each event type within the time range and calculate MEWS score based on that in FE.

**Comment by nihal467** [comment] 2024-08-19 10:59
@r-nikhilkumar are you interested in working on this issue, feel free to reach out to @rithviknishad if you have any query or post a message in the care_general as well

**Comment by r-nikhilkumar** [comment] 2024-09-06 18:57
> @r-nikhilkumar are you interested in working on this issue, feel free to reach out to @rithviknishad if you have any query or post a message in the care_general as well

@nihal467 Currently I'm having some placement exams and SIH finals, so I'm currently not available, once exams will be over, I'll be on this issue for sure

**Comment by rithviknishad** [comment] 2024-09-25 14:21
@aparnacoronasafe just wanted to confirm if whether this needs to be shown in the patient list and also whether patient list needs to be sortable based on MEWS score.

cc: @vigneshhari

**Comment by aparnacoronasafe** [comment] 2024-09-25 15:56
Yes. 

MEWS score is only relevant for patients admitted to ICU. 

It would be a goos feature to show MEWS score on patient list and also allow users to sort patients by MEWS Score.

**Comment by nihal467** [comment] 2024-12-31 08:02
non-relevant to current develop

**Closed as not planned by nihal467** 2024-12-31 08:02 UTC
Labels: Backend, Frontend
