### ISSUE TITLE
Assigning patient to doctor/nurse: consultation

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6276] opened 2023-09-13 02:48 UTC
**Is your feature request related to a problem? Please describe.**
Today, CARE only allows for a patient to be assigned to a doctor if user says Yes to "Is Telemedicine required for the patient?"
https://care.coronasafe.in/facility/e3311351-3ec9-4cb0-a6e1-902225ac705c/patient/4d2080f9-8bd4-4744-a138-14a53b195fef/consultation/ec278c38-dd7a-406b-a943-36932d30a6ff/update

But in our current usecases, TeleICU and homecare, Doctors or nurses may be assigned to a patient for specialist remote consultation/ home-visit duties. 

**Describe the solution you'd like**

- [ ] Change "Is Telemedicine required for the patient?" to "Assign care providers to the patient", when selected. have two dropdowns "Assign patient to doctor", and "assign patient to nurse".   Allow assignment of up to 3 doctors and 2 nurses per patient.
- [ ] On patient dashboard (https://care.coronasafe.in/facility/e3311351-3ec9-4cb0-a6e1-902225ac705c/patient/4d2080f9-8bd4-4744-a138-14a53b195fef/consultation/ec278c38-dd7a-406b-a943-36932d30a6ff) below "verfied by", add "assigned to"- name od doc/nurse (doctor's skill/nurse)

Such assignment shall stop once the consultation is ended with a discharge.

**Comment by nihal467** [comment] 2023-11-27 05:47
- [ ] We can only assign one user to a patient; having multiple users assigned to a patient is not currently feasible. @aparnacoronasafe 

_Discussion note on 27/11/2023 - Engineering Call_

**Comment by aparnacoronasafe** [comment] 2023-11-27 08:21
> * [ ]  We can only assign one user to a patient; having multiple users assigned to a patient is not currently feasible. @aparnacoronasafe
> 
> _Discussion note on 27/11/2023 - Engineering Call_

Is it 1 nurse & 1 doctor? Or just 1 nurse/doctor

**Comment by nihal467** [comment] 2023-11-28 20:00
@aparnacoronasafe currently we support only 1 doctor user and we can modify to support either 1 nurse or 1 doctor user

**Comment by aparnacoronasafe** [comment] 2024-01-22 06:28
Can we then have separate fields 
"Assign a nurse to the patient" - assign 1 nurse
"Assign a doctor to the patient" - assign 1 doctor

Is this possible? 

This is particularly important for homecare where nurses are allocated for patients, alongside doctor.

**Comment by Ashesh3** [comment] 2024-02-19 06:42
We've discussed enhancing the `PatientRegistration` model to support a more flexible patient assignment system. The consensus is to move beyond the initial proposal of capping assignments to up to 3 doctors and 2 nurses per patient. Instead, we will implement a one-to-many relationship that allows for assigning any number of doctors or nurses as needed to a patient, thus removing any specific limitations on the number of care providers. This change will better accommodate the diverse needs of our TeleICU and homecare services and align with the requirements detailed in the discussion.

In addition to adjusting the model relationship, this update will necessitate both backend and frontend changes to support the enhanced functionality. This includes updates to authorization, filters, and any other necessary adjustments to ensure a smooth and functional implementation.

**Comment by aparnacoronasafe** [comment] 2024-08-19 07:23
@nihal467 

We urgently need to allow assignment of 1 doc/nurse to the patient. 

Where is this stuck?

**Comment by sanjayh-2022** [comment] 2024-12-12 08:57
@bodhish Can I work on this issue ?

**Comment by nihal467** [comment] 2024-12-16 11:10
@sanjayh-2022 the issue is assigned to you

**Comment by sanjayh-2022** [comment] 2024-12-24 14:26
@nihal467  Can you just brief me about the issue, please?

**Comment by Jacobjeevan** [comment] 2024-12-30 16:00
@sanjayh-2022 Closing as no longer relevant.

**Closed as not planned by Jacobjeevan** 2024-12-30 16:00 UTC
