### ISSUE TITLE
Multi selection of investigations not working in Patient log lab results

### ISSUE THREAD

**Issue by rohitlingarker** [coronasafe/care_fe#9144] opened 2024-11-16 19:34 UTC
**Describe the bug**
When Logging the lab results in the Patient investigation tab, we cannot select multiple investigations at once. Atmost we can select 2 (that is by double clicking one option and then clicking on second one, this may also be a bug). 
When selecting multiple investigations from the dropdown in the multiselect form for uploading lab results, the input form for previously selected investigations gets hidden. However, if those forms were filled, their data is still processed during form submission, and empty form also getting submitted.

**To Reproduce**

1. Go to patient tab
2. Select any active patient
3. Go to investigations tab
4. Click on `Log Lab Results`
5. Double click any option from the search drop down and click another option
6. See error
7. Select a option and fill the following form that is given 
8. Select another option from dropdown and see error(previous filled form gets hidden)
9. Submit the form , the data gets processed

**Screenshots**
https://github.com/user-attachments/assets/8e586585-9382-459f-a262-efc2734656bd

**Desktop (please complete the following information):**

- Version 129.0.6668.90 (Official Build) (64-bit)

**Additional context**
I would like to be assigned to this issue and requesting for expected behaviour

**Comment by Jacobjeevan** [comment] 2024-11-19 08:49
(1) Should be able to select multiple investigations
(2) Pass the data to backend only if investigation is still selected

**Comment by rajku-dev** [comment] 2024-11-24 12:57
> (1) Should be able to select multiple investigations (2) Pass the data to backend only if investigation is still selected

when user selects one investigation group like 'Biochemistry Test', it shows all tests under 'Biochemistry Test', next if user selects 'FBS' which comes under 'Biochemistry Test', what should be the expected behavior, only one 'FBS' should be shown or all the tests of 'Biochemistry Test' should be shown, since user has selected 'Biochemistry Test' before.
@Jacobjeevan

**Comment by Jeffrin2005** [comment] 2024-12-05 09:49
@nihal467 @Jacobjeevan   I Would like to work on this issue. Would you assign to me?

**Comment by nihal467** [comment] 2024-12-09 12:20
@Jeffrin2005 are you still interested to work on this,

**Comment by Jeffrin2005** [comment] 2024-12-09 12:22
@nihal467  Yes .  I Would like to work on this issue

**Comment by nihal467** [comment] 2024-12-09 12:23
@rohitlingarker are you working on this issue

**Comment by nihal467** [comment] 2024-12-09 12:35
@rohitlingarker unassigning you due to inactivity and assign it to @Jeffrin2005

**Closed as not planned** 2024-12-31 07:17 UTC
Labels: bug
