### ISSUE TITLE
Facility profile: Add Logo and header

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#8425] opened 2024-08-26 13:22 UTC
**Is your feature request related to a problem? Please describe.**
CARE allows users to auto generate and print various summaries and reports. 

The format of these is not very good because it lacks the hospitals' Logo and a proper header. The printouts do not look like official documents because of such bad formatting.

**Describe the solution you'd like**
In Facility registration/updation form (https://care.coronasafe.in/facility/4f83b5ff-7683-499f-b330-3f49b85fef23/update) add an optional field to upload Logo and a large text field for the hospital to add text that would form the header of such summaries. 

- [ ] Upload logo
- [ ] Add text for header

The "text for header" will most likely have the full name of the hospital, Branch/Location. In Case of Govt. hospital, on top it would also have the name of the health department. Allow users to pick from an option of 3 text sizes (S/M/L) to present the text in, with line breaks

Eg of a header

"Government of Nagaland (text size- M)
Naga Hospital Authority (Text size L)
Kohima (Text Size S)"

The format of the header may be as below:
https://docs.google.com/document/d/1nohiHW6DOX34ViVxRPy_uxrCVNWu3npSncSelSbHj0Q/edit?usp=sharing 

**Describe alternatives you've considered**

**Additional context**

**Comment by AdityaJ2305** [comment] 2024-08-26 15:49
Hey @aparnacoronasafe while reproducing the facility update page I am getting this toast 
You don't have permission to perform this action. Contact the admin
and can't see the add facility button I think due to same reason

**Comment by shivankacker** [comment] 2024-08-30 23:58
@AdityaJ2305 the facility is not present in the district you are logging into.

You can reproduce the issue with another facility though, the link provided is just for example

**Comment by bodhish** [comment] 2024-09-06 09:04
Does all hospitals have a logo @aparnacoronasafe?

I would say use the logo configured in the instance. (State logo) and add just the name and address of the facility.

Here are few examples from Ehealth. 


### Prescription
<img width="929" alt="image" src="https://github.com/user-attachments/assets/31e008ef-26a5-48e5-97e4-0032b95a9ad7">

### Lab report
<img width="948" alt="image" src="https://github.com/user-attachments/assets/c3ab5bd9-68ff-4a00-9455-0409d6d85a27">

### Token
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/34f37eb6-da77-433d-9523-06054c92083d">

**Comment by aparnacoronasafe** [comment] 2024-09-06 15:56
@bodhish For govt, what you are saying is mostly right. But even their there are exceptions where this doesnt work. Eg: with 10BedICU implementation, all hospitals under health dept. will have the same logo, but the medical colleges may insist on having their own Logo
eg: 
![Screenshot 2024-09-06 at 9 24 33 PM](https://github.com/user-attachments/assets/280975f5-03b9-4f75-8251-7e150d5c1c2a)

Also for adopters in Pvt sector, this will be required at hospital level. For eg IAPC instance, all facilities would want their own Logos.

**Comment by bodhish** [comment] 2024-09-06 16:02
Can you define the logo dimensions and colour etc? 

Additional context: I don't think we will run multiple hospitals in 1 instance other than for 10bedICU; 

Do we have a requirement from a facility for this? If not, lets part this for a while

**Comment by aparnacoronasafe** [comment] 2024-09-06 16:24
@bodhish The palliative care deployment for IAPC would also require this feature

**Comment by athulmanuel** [comment] 2024-09-06 18:04
Palliative care will definitely need for IAPC instance. 
@bodhish @aparnacoronasafe  - might need It in govt setting as well as some of the hospitals have their own logo and in some, they will have. LSG logo inaddition. - Logos can be the same as the profile picture of the facility so that they enter the logo of the facility if any at all

**Comment by athulmanuel** [comment] 2024-09-06 18:25
We also have an option to leave a space for a header according the the size of the paper. 
Eg - prescriptions will be small A5
Discharge will be A4. 
Bill will be small a5 or even smaller 
Lab might be different size and so on

**Comment by aparnacoronasafe** [comment] 2024-09-09 07:09
Size of the paper may be entered when print command is given at a system level right? I don't think CARE needs to build that in. We could optimise the design of the summaries for this size.

**Comment by aparnacoronasafe** [comment] 2024-09-09 07:16
> Can you define the logo dimensions and colour etc?

I recommend we allow facilities to update logo in PNG, SVG, JPEG formats of up to 200KB file size with a max of 500px * 500px. 

We must enable logos in colour.

**Comment by bodhish** [comment] 2024-09-19 09:15
<img width="492" alt="image" src="https://github.com/user-attachments/assets/28631048-882f-4d83-b652-769f11c971c5">
<img width="554" alt="image" src="https://github.com/user-attachments/assets/41e3f818-e793-4b0e-95a9-98adde77732d">


The new designs will have well formatted hospital info, I am going in favour of not adding a logo now, we will consider the logo once we complete the HMIS changes. 
Closing this issue for now. 

CC: @athulmanuel @aparnacoronasafe

**Closed as completed by bodhish** 2024-09-19 09:15 UTC

**Comment by athulmanuel** [comment] 2024-09-19 09:24
Ok. Is there an option to leave space for header
