### ISSUE TITLE
"No Data Available" message missing for Consultation and Sample Test History.

### ISSUE THREAD

**Issue by FarhanMig24** [coronasafe/care_fe#7530] opened 2024-04-03 11:18 UTC
**Is your feature request related to a problem? Please describe.**
In the patient tab, when one tries to look for details for patients with no consultation or sample test history, **no appropriate messages** are provided for the empty option unlike it has been provided for medical and policy details if there aren't any.

![issue1](https://github.com/coronasafe/care_fe/assets/92749027/f9c6386d-a872-4b14-a70d-d0772bfb803e)

**Describe the solution you'd like**
Need to check the **paginated list size** and appropriate message to be shown.

**Expected Behavior**
![solution1](https://github.com/coronasafe/care_fe/assets/92749027/79084c52-8e93-42e9-b2ae-e0d91ff5de50)

Please review the issue. @rithviknishad @nihal467

**Comment by rithviknishad** [comment] 2024-04-03 12:04
Closing as duplicate of #7501

**Closed as not planned by rithviknishad** 2024-04-03 12:04 UTC
