### ISSUE TITLE
Optimize Component Refresh Behavior in User Tab for Username Search

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9402] opened 2024-12-13 04:42 UTC
**Describe the bug**

- [ ] When searching for a username in the User Tab, all components on the page (except the side navigation) are being refreshed. This behavior is incorrect. Ideally, only the user card list and the total user count should be refreshed. Components such as advanced filters, like buttons, and other static elements should remain unaffected by the search operation.

**To Reproduce**

1. Go to user tab
2. search for a username
3. See error

**Expected behavior**

- [ ] Only the user card list and total user count should refresh; all other components should remain static.

**Screenshots**

![Image](https://github.com/user-attachments/assets/74080f59-b460-4c47-9a55-fa8dde9901cc)

**Comment by awaiskhan21** [comment] 2024-12-13 04:43
i would like to work on this issue @nihal467 can you assign it to me please!!

**Comment by rithviknishad** [comment] 2024-12-13 04:58
Duplicate of #9398 

cc: @nihal467

**Closed as not planned by rithviknishad** 2024-12-13 04:58 UTC
