### ISSUE TITLE
Improve the Patient age reflection in the consultation page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7451] opened 2024-03-21 20:56 UTC
**Describe the bug**

On the patient consultation page, the patient's age is shown only in years. If the age is less than 1 year, it is shown as 0.

**To Reproduce**

1. Go to patient consultation page of a patient who's age is less than 1 year old
2. See error

**Expected behavior**

On the patient consultation page, if the patient's age is <1 year, it should be shown in months and days. (Similar behavior is already implemented on the patient detail page; refer to it)

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/75531ab1-a916-4c83-9406-f9c6b9ab3dc1)
![image](https://github.com/coronasafe/care_fe/assets/57055998/09a0c571-39f8-48c2-9395-73b70687f43b)

**Comment by rash-27** [comment] 2024-03-21 21:03
I would like to work on this issue

**Comment by rithviknishad** [comment] 2024-03-22 05:53
Closing as duplicate of https://github.com/coronasafe/care_fe/issues/7383

**Closed as not planned by rithviknishad** 2024-03-22 05:53 UTC
